### ISSUE TITLE
Axolotl missing libzkgroup_linux_amd64.so

### ISSUE THREAD

**Issue by Torbuntu** [flathub/org.nanuc.Axolotl#3]
After installing from flathub Axolotl will not launch. It immediately fails with the following error.

Desktop:
```
axolotl: error while loading shared libraries: libzkgroup_linux_amd64.so: cannot open shared 
object file: No such file or directory
```
PinePhone:
```
axolotl: error while loading shared libraries: libzkgroup_linux_arm64.so: cannot open shared 
object file: No such file or directory
```

I also tried building the qt flatpak from the github repo directly and get the same problem.

**Comment by olof-nord** [comment]
Thanks for bringing this up! The new version needs a new library, which wasn't needed before. The upgrade is now rolled back in favour of the previous version.

**Comment by olof-nord** [comment]
Hello @Torbuntu, since your comment we have released a few versions. The library issue was present in the 0.9.x releases and got solved with the 1.x releases: could you try out with 1.2.0?

**Comment by Torbuntu** [comment]
Thank you for following up with me! I installed it from flathub and it indeed now launches. 
I no longer have my older phone number which had an account on signal to test it, but it seems to work up to the registration point anyway now.

Thanks again!

**Comment by olof-nord** [comment]
Happy to hear! Closing this issue then :+1:
